wandb_version: 1

imbalance ratio:
  desc: null
  value: 100
method:
  desc: null
  value: ERM
_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711653117.0
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 63
      2:
      - 1
      - 41
      - 49
      - 55
      - 63
      3:
      - 16
      - 23
      4: 3.11.7
      5: 0.16.5
      8:
      - 3
      - 5
      13: windows-amd64
