general: 
  dataset_name: organsmnist
  num_classes: 11
datasets:
  imbalance_ratio: 10
  head: 3
  medium: 6
  tail: 11
  img_path: '/mnt/sda/julie/datasets/medmnist/images/organsmnist_224/'
  train:
    np_path: '/mnt/sda/julie/projects/OpenMedLongTailed/numpy/medmnist/organsmnist_train.npy'
    dict_path: '/mnt/sda/julie/projects/OpenMedLongTailed/numpy/medmnist/organsmnist_dic.npy'
  val:
    np_path: '/mnt/sda/julie/projects/OpenMedLongTailed/numpy/medmnist/organsmnist_val.npy'
    dict_path: '/mnt/sda/julie/projects/OpenMedLongTailed/numpy/medmnist/organsmnist_dic.npy'
  test:
    np_path: '/mnt/sda/julie/projects/OpenMedLongTailed/numpy/medmnist/organsmnist_test.npy'
    dict_path: '/mnt/sda/julie/projects/OpenMedLongTailed/numpy/medmnist/organsmnist_dic.npy'
  transforms:
    train: 'strong'
    val_test: 'normal'