general: 
  dataset_name: bloodmnist
  num_classes: 8
datasets:
  imbalance_ratio: 10
  head: 3
  medium: 5
  tail: 8
  img_path: '/mnt/sda/julie/datasets/medmnist/images/bloodmnist_224/'
  train:
    np_path: '/mnt/sda/julie/projects/OpenMedLongTailed/numpy/medmnist/bloodmnist_train.npy'
    dict_path: '/mnt/sda/julie/projects/OpenMedLongTailed/numpy/medmnist/bloodmnist_dic.npy'
  val:
    np_path: '/mnt/sda/julie/projects/OpenMedLongTailed/numpy/medmnist/bloodmnist_val.npy'
    dict_path: '/mnt/sda/julie/projects/OpenMedLongTailed/numpy/medmnist/bloodmnist_dic.npy'
  test:
    np_path: '/mnt/sda/julie/projects/OpenMedLongTailed/numpy/medmnist/bloodmnist_test.npy'
    dict_path: '/mnt/sda/julie/projects/OpenMedLongTailed/numpy/medmnist/bloodmnist_dic.npy'
  transforms:
    train: 'strong'
    val_test: 'normal'